version: "3.9"
services:
    safety-assessment:
        build: src/
        container_name: safety-assessment
        depends_on:
            -   postgres
        ports:
            - "8888:8888"
    postgres:
        image: postgis/postgis
        container_name: simra_db
        volumes:
            - ./db/simra.sql:/docker-entrypoint-initdb.d/init-user-db.sql:ro
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: simra
            POSTGRES_USER: simra
            POSTGRES_PASSWORD: simra12345simra
            