FROM python:slim-buster

COPY .. .

WORKDIR .

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

RUN pip install -r requirements.txt

RUN pip install jupyterlab

ENV PYTHONPATH "${PYTHONPATH}:/"

RUN python ./app/main.py

CMD ["python-lab"]
